[project]
name = "pontocar"
version = "0.1.0"
requires-python = ">=3.14,<3.15"
dependencies = [
    "asgiref==3.12.1",
    "Django==6.0.7",
    "django-cors-headers==4.9.0",
    "django-filter==26.1",
    "django-storages[s3]==1.14.6",
    "djangorestframework==3.17.1",
    "djangorestframework-simplejwt==5.5.1",
    "pillow==12.3.0",
    "psycopg2-binary==2.9.12",
    "PyJWT==2.13.0",
    "python-dotenv==1.2.2",
    "sqlparse==0.5.5",
    "tzdata==2026.3",
]

[tool.vercel]
entrypoint = "config.wsgi:application"