# Generated by Django 6.0.7 on 2026-08-17 21:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor_proposta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDENTE', 'Proposta Pendente'), ('EM_NEGOCIACAO', 'Em Negociação'), ('CONCLUIDA', 'Venda Concluída'), ('CANCELADA', 'Cancelada/Recusada')], default='PENDENTE', max_length=20)),
                ('data_proposta', models.DateTimeField(auto_now_add=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negociacoes', to='veiculos.veiculo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
