# Generated by Django 6.0.7 on 2026-08-13 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculos', '0002_remove_veiculo_vendedor_veiculo_proprietario_atual_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_proposta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDENTE', 'Proposta Pendente'), ('EM_NEGOCIACAO', 'Em Negociação'), ('CONCLUIDA', 'Venda Concluída'), ('CANCELADA', 'Cancelada/Recusada')], default='PENDENTE', max_length=20)),
                ('data_proposta', models.DateTimeField(auto_now_add=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negociacoes', to='veiculos.veiculo')),
            ],
        ),
    ]
