# Generated by Django 6.0.7 on 2026-08-17 21:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('ano_fabricacao', models.IntegerField()),
                ('ano_modelo', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quilometragem', models.IntegerField(default=0)),
                ('placa', models.CharField(max_length=7, unique=True)),
                ('cor', models.CharField(max_length=30)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('PENDENTE', 'Pendente'), ('VENDIDO', 'Vendido / Inativo')], default='DISPONIVEL', max_length=15)),
                ('quantidade_proprietarios', models.IntegerField(default=1)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('proprietario_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veiculos_na_garagem', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoVeiculo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motivo', models.CharField(choices=[('VENDA_SITE', 'Site PontoCar'), ('VENDA_LOJA', 'Venda em loja'), ('VENDA_PRESENCIAL', 'Venda presencialmente'), ('OUTROS', 'Outros'), ('ARREPENDIMENTO', 'Arrependi de vender'), ('MALSUCEDIDA', 'Venda malsucedida'), ('CADASTRO', 'Veículo Cadastrado no Sistema')], max_length=20)),
                ('mensagem_automatica', models.TextField(blank=True)),
                ('data_evento', models.DateTimeField(auto_now_add=True)),
                ('dono_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_vendas', to=settings.AUTH_USER_MODEL)),
                ('novo_dono', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_compras', to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='veiculos.veiculo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
