# Generated by Django 6.0.7 on 2026-08-11 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='vendedor',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='proprietario_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veiculos_na_garagem', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='quantidade_proprietarios',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='status',
            field=models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('PENDENTE', 'Pendente'), ('VENDIDO', 'Vendido / Inativo')], default='DISPONIVEL', max_length=15),
        ),
        migrations.CreateModel(
            name='HistoricoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('VENDA_SITE', 'Site PontoCar'), ('VENDA_LOJA', 'Venda em loja'), ('VENDA_PRESENCIAL', 'Venda presencialmente'), ('OUTROS', 'Outros'), ('ARREPENDIMENTO', 'Arrependi de vender'), ('MALSUCEDIDA', 'Venda malsucedida'), ('CADASTRO', 'Veículo Cadastrado no Sistema')], max_length=20)),
                ('mensagem_automatica', models.TextField(blank=True)),
                ('data_evento', models.DateTimeField(auto_now_add=True)),
                ('dono_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_vendas', to=settings.AUTH_USER_MODEL)),
                ('novo_dono', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_compras', to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='veiculos.veiculo')),
            ],
        ),
    ]
