# Generated by Django 6.0.7 on 2026-08-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='cambio',
            field=models.CharField(blank=True, choices=[('AUTOMATICO', 'Automático'), ('MANUAL', 'Manual')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='combustivel',
            field=models.CharField(blank=True, choices=[('FLEX', 'Flex'), ('DIESEL', 'Diesel'), ('HIBRIDO_ELETRICO', 'Híbrido/Elétrico')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='versao',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
