# Generated by Django 6.0.7 on 2026-08-21 22:44

import apps.veiculos.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0002_veiculo_cambio_veiculo_combustivel_veiculo_versao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='cambio',
            field=models.CharField(blank=True, choices=[('MANUAL', 'Manual'), ('AUTOMATICO', 'Automático'), ('CVT', 'CVT')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='combustivel',
            field=models.CharField(blank=True, choices=[('FLEX', 'Flex'), ('GASOLINA', 'Gasolina'), ('DIESEL', 'Diesel'), ('ELETRICO', 'Elétrico'), ('HIBRIDO', 'Híbrido')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='versao',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.CreateModel(
            name='FotoVeiculo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imagem', models.ImageField(upload_to=apps.veiculos.models.foto_veiculo_upload_path)),
                ('principal', models.BooleanField(default=False)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('texto_alternativo', models.CharField(blank=True, max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='veiculos.veiculo')),
            ],
            options={
                'ordering': ['ordem', 'criado_em'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('principal', True)), fields=('veiculo',), name='uq_foto_principal_por_veiculo')],
            },
        ),
    ]
