# Generated by Django 6.0.7 on 2026-08-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0003_alter_veiculo_cambio_alter_veiculo_combustivel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veiculo',
            options={'permissions': [('pode_moderar_veiculo', 'Pode aprovar ou rejeitar anúncios de veículo')]},
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_ANALISE', 'Em Análise'), ('DISPONIVEL', 'Disponível'), ('RESERVADO', 'Reservado'), ('VENDIDO', 'Vendido'), ('REJEITADO', 'Rejeitado'), ('PAUSADO', 'Pausado'), ('ARQUIVADO', 'Arquivado')], default='DISPONIVEL', max_length=15),
        ),
    ]
