# Generated by Django 6.0.7 on 2026-09-11 22:49

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitBucket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chave', models.CharField(db_index=True, max_length=64, unique=True)),
                ('contador', models.PositiveIntegerField(default=0)),
                ('inicio_janela', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'contador de limite de requisições',
                'verbose_name_plural': 'contadores de limite de requisições',
            },
        ),
    ]
