# Generated by Django 6.0.7 on 2026-08-10 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=100)),
                ('razao_social', models.CharField(max_length=150)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('tipo_empresa', models.CharField(choices=[('REVENDA', 'Revenda de Veículos'), ('CONCESSIONARIA', 'Concessionária Autorizada'), ('OFICINA', 'Oficina Mecânica'), ('SEGURADORA', 'Seguradora'), ('CORRETORA', 'Corretora de Seguros')], default='REVENDA', max_length=20)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=9)),
                ('logradouro', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='localizacao', to='empresas.empresa')),
            ],
        ),
    ]
