# Generated by Django 6.0.7 on 2026-08-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
    ]
