# Generated by Django 6.0.7 on 2026-08-21 22:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_empresa_ativa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificacaoEmpresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_documento', models.CharField(max_length=150)),
                ('caminho_documento', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada'), ('SUSPENSA', 'Suspensa')], default='PENDENTE', max_length=20)),
                ('observacao_solicitante', models.TextField(blank=True)),
                ('observacao_administrador', models.TextField(blank=True)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('analisada_em', models.DateTimeField(blank=True, null=True)),
                ('analisada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verificacoes_analisadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verificacoes', to='empresas.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
