# Generated by Django 6.0.7 on 2026-08-21 22:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguros', '0001_initial'),
        ('veiculos', '0003_alter_veiculo_cambio_alter_veiculo_combustivel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seguro',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ApoliceSeguro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor_mensal', models.DecimalField(decimal_places=2, help_text='Valor real contratado. Pode diferir do valor_referencia do plano.', max_digits=10)),
                ('inicio_vigencia', models.DateField()),
                ('fim_vigencia', models.DateField()),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('EXPIRADA', 'Expirada'), ('CANCELADA', 'Cancelada')], default='ATIVA', max_length=10)),
                ('contratante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apolices', to=settings.AUTH_USER_MODEL)),
                ('seguro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apolices', to='seguros.seguro')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apolices', to='veiculos.veiculo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CotacaoSeguro',
        ),
    ]
