# Generated by Django 6.0.7 on 2026-08-21 22:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculos', '0002_veiculo_cambio_veiculo_combustivel_veiculo_versao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritado_por', to='veiculos.veiculo')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('usuario', 'veiculo'), name='unique_favorito_usuario_veiculo')],
            },
        ),
    ]
